stages:
  - setup

variables:
  PYTHON_PATH: "/home/todd/.local/share/virtualenvs/tm-trivia-OAypQb65/bin"
  NVM_PATH: "/home/gitlab-runner/.nvm/versions/node/v16.20.1/bin"

setup-job:
  stage: setup
  # environment: production
  script:
    - cd /opt/tm-trivia
    - git fetch origin main && git pull origin main
    - $NVM_PATH/npm i && $NVM_PATH/npm run build
    - pipenv install