# predefined variables: https://docs.gitlab.com/16.2/ee/ci/variables/predefined_variables.html
# keywor reference: https://docs.gitlab.com/16.2/ee/ci/yaml/index.html

stages:
  - deploy

variables:
  PYTHON: "/home/gitlab-runner/.local/share/virtualenvs/tm-trivia-OAypQb65/bin/python"
  NPM: "/home/gitlab-runner/.nvm/versions/node/v16.20.1/bin/npm"

# TODO:
# when moving to tags update the job (or crate a new one?) so that th git step checks outs the new tag
staging-deploy-job:
  stage: deploy
  script:
    - cd /opt/tm-trivia
    # pull the updated repo
    - git reset --hard && git fetch origin main && git pull origin main
    # update and build SvelteKit
    - $NPM i && $NPM run build
    # update and build Django
    - pipenv install
    - cd server
    - $PYTHON manage.py collectstatic --no-input
    - $PYTHON manage.py migrate
    # restart services
    - sudo systemctl restart tm-trivia.service
    - sudo systemctl restart tm-trivia-api.service
  environment: staging
  rules:
     # only run when merging into main
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      #  when: manual # force manual deployment (I thnk this adds a button the the ui?)

     # TODO: use this when we move to using tags for releases
     # - if: $CI_COMMIT_TAG
