stages:
  - setup

variables:
  PYTHON: "/home/gitlab-runner/.local/share/virtualenvs/tm-trivia-OAypQb65/bin/python"
  NPM: "/home/gitlab-runner/.nvm/versions/node/v16.20.1/bin/npm"

setup-job:
  stage: setup
  # environment: production
  script:
    - cd /opt/tm-trivia
    # pull the updated repo
    - git reset --hard && git fetch origin main && git pull origin main
    # update and build SvelteKit
    - $NPM i && $NPM run build
    # update and build Django
    - pipenv install
    - cd server
    - $PYTHON manage.py collectstatic --no-input
    - $PYTHON manage.py migrate
    # restart services
    - sudo systemctl restart tm-trivia.service
    - sudo systemctl restart tm-trivia-api.service