stages:
  - setup

setup-job:
  stage: setup
  # environment: production
  script:
    - cd /opt/tm-trivia
    - git fetch origin main && git pull origin main
    - npm i && npm run build
    - pipenv install
    - cd server
    - pipenv run python manage.py collectstatic --no-input
    - pipenv run python manage.py migrate

    # TODO decide how to handel sudo
    # - sudo systemctl restart tm-trivia.service
    # - sudo systemctl restart tm-trivia-api.service