stages:
  - setup

variables:
  PYTHON_PATH: "/home/todd/.local/share/virtualenvs/tm-trivia-OAypQb65/bin/python"
  NVM_PATH: "/home/gitlab-runner/.nvm/versions/node/v16.20.1/bin"

setup-job:
  stage: setup
  # environment: production
  script:
    - cd /opt/tm-trivia
    # pull the updated repo
    - fetch origin main && git pull origin main
    # update and build SvelteKit
    - $NVM_PATH/npm i && $NVM_PATH/npm run build
    # update and build Django
    - pipenv pipenv install
    - cd server
    - $PYTHON_PATH manage.py collectstatic --no-input
    - $PYTHON_PATH manage.py migrate
    # restart services