# Generated by Django 4.2a1 on 2023-03-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_alter_leaderboardentry_leaderboard_type_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.team",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_reveal_questions",
            field=models.BooleanField(default=False),
        ),
    ]
