# Generated by Django 4.1b1 on 2022-11-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_active_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_reveal_questions",
            field=models.BooleanField(default=False),
        ),
    ]
