# Generated by Django 4.1.3 on 2022-12-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_response"),
        ("user", "0003_user_auto_reveal_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="active_team_id",
        ),
        migrations.AddField(
            model_name="user",
            name="active_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.team",
            ),
        ),
    ]
