# Generated by Django 4.2.2 on 2023-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="screen_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
