# Generated by Django 4.1a1 on 2022-07-02 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200, unique=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="members",
                        related_query_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
