# Generated by Django 4.2a1 on 2023-03-02 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="triviaevent",
            name="players",
            field=models.ManyToManyField(
                blank=True, related_name="players", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tiebreakerquestion",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiebreaker_questions",
                to="game.game",
            ),
        ),
        migrations.AddField(
            model_name="tiebreakerquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.question"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="game.triviaevent",
            ),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="game_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.gamequestion"
            ),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="game.team",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="accepted_answers",
            field=models.ManyToManyField(
                blank=True, related_name="accepted_answers", to="game.questionanswer"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="display_answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="display_answer",
                to="game.questionanswer",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="primary_host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_entries",
                related_query_name="leaderboard_entry",
                to="game.triviaevent",
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="leaderboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                related_query_name="leaderboard_entry",
                to="game.leaderboard",
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="game.team",
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboards",
                to="game.triviaevent",
            ),
        ),
        migrations.AddField(
            model_name="gameround",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_rounds",
                to="game.game",
            ),
        ),
        migrations.AddField(
            model_name="gamequestion",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_questions",
                to="game.game",
            ),
        ),
        migrations.AddField(
            model_name="gamequestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.question"
            ),
        ),
        migrations.AddField(
            model_name="eventroundstate",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_states",
                to="game.triviaevent",
            ),
        ),
        migrations.AddField(
            model_name="eventquestionstate",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_states",
                to="game.triviaevent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaderboardentry",
            unique_together={("team", "event", "leaderboard_type")},
        ),
    ]
