# Generated by Django 4.1b1 on 2022-11-10 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_team_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("block_code", models.CharField(default="", max_length=150)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_used", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-date_used", "title"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question_type",
                    models.IntegerField(
                        choices=[
                            (0, "General Knowledge"),
                            (1, "Themed Round"),
                            (2, "Word Play"),
                            (3, "Image Round"),
                            (4, "Lightning Round"),
                            (5, "Sound Round"),
                            (6, "Tiebreaker"),
                        ],
                        default=0,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("display_answer", models.CharField(max_length=255)),
                (
                    "answer_notes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TriviaEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "join_code",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("current_round_number", models.IntegerField(default=1)),
                ("current_question_number", models.IntegerField(default=1)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=128)),
                ("round_description", models.TextField(blank=True, default="")),
                ("round_number", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_rounds",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("round_number", models.IntegerField()),
                ("question_number", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_questions",
                        to="game.game",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRoundState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("round_number", models.IntegerField()),
                ("locked", models.BooleanField(default=False)),
                ("scored", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_states",
                        to="game.triviaevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventQuestionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("question_number", models.IntegerField()),
                ("round_number", models.IntegerField()),
                ("question_displayed", models.BooleanField(default=False)),
                ("answer_displayed", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_states",
                        to="game.triviaevent",
                    ),
                ),
            ],
        ),
    ]
