# Generated by Django 4.2rc1 on 2023-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_leaderboardentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="triviaevent",
            name="event_complete",
            field=models.BooleanField(default=False),
        ),
    ]
