# Generated by Django 4.2.1 on 2023-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_triviaevent_event_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="use_sound",
            field=models.BooleanField(default=True),
        ),
    ]
