# Generated by Django 4.2.1 on 2023-05-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_game_use_sound"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="primary_host",
        ),
        migrations.AddField(
            model_name="location",
            name="use_sound",
            field=models.BooleanField(default=True),
        ),
    ]
