# Generated by Django 4.2.1 on 2023-06-13 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_remove_location_primary_host_location_use_sound"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameround",
            options={"ordering": ["game", "round_number"]},
        ),
        migrations.AlterModelOptions(
            name="leaderboardentry",
            options={
                "ordering": [
                    "-event",
                    "rank",
                    "tiebreaker_rank",
                    "pk",
                    "-leaderboard_type",
                ],
                "verbose_name_plural": "Leaderboard Entries",
            },
        ),
    ]
