# Generated by Django 4.2.1 on 2023-06-13 12:23

from django.db import migrations, models
import game.models.trivia_event


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0010_alter_gameround_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="active_through",
            field=models.DateField(default=game.models.trivia_event.get_end_of_week),
        ),
    ]
