# Generated by Django 4.2.1 on 2023-06-13 14:45

from django.db import migrations, models
import game.models.trivia_event


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0011_game_active_through"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="active_through",
            field=models.DateField(
                blank=True, default=game.models.trivia_event.get_end_of_week, null=True
            ),
        ),
    ]
