# Generated by Django 4.2.1 on 2023-06-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0012_alter_game_active_through"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="password",
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
