# Generated by Django 4.2.2 on 2023-07-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0014_leaderboardentry_points_adjustment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardentry",
            name="points_adjustment",
            field=models.FloatField(default=0),
        ),
    ]
