# Generated by Django 4.2a1 on 2023-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_squashed_0014_alter_leaderboardentry_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardentry",
            name="leaderboard_type",
            field=models.IntegerField(choices=[(0, "Host"), (1, "Public")]),
        ),
        migrations.AlterField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
