# Generated by Django 4.2.2 on 2023-07-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0016_leaderboardentry_tied_for_rank_tiebreakerresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tiebreakerresponse",
            name="leaderboard_entry",
        ),
        migrations.RemoveField(
            model_name="tiebreakerresponse",
            name="tiebreaker_question",
        ),
        migrations.AddField(
            model_name="tiebreakerresponse",
            name="game_question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.gamequestion",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TiebreakerQuestion",
        ),
    ]
