# Generated by Django 4.2.2 on 2023-08-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0018_tiebreakerresponse_round_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="tiebreaker_round_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
