# Generated by Django 4.2.2 on 2023-08-16 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0022_question_question_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="description",
        ),
    ]
