# Generated by Django 4.2.4 on 2023-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0023_remove_game_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
