# Generated by Django 4.2.5 on 2023-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0025_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="time",
            field=models.TimeField(),
        ),
    ]
