# Generated by Django 4.2.5 on 2023-09-07 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0026_alter_chatmessage_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="time",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
