# Generated by Django 4.2.5 on 2023-09-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0027_remove_chatmessage_time_alter_chatmessage_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["-event", "team", "pk"]},
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_host_message",
            field=models.BooleanField(default=False),
        ),
    ]
