# Generated by Django 4.2.5 on 2023-09-14 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0030_alter_chatmessage_options_gamequestionnote"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GameQuestionNote",
            new_name="TeamNote",
        ),
    ]
