# Generated by Django 4.2.6 on 2023-10-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0034_alter_changelog_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changelog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="triviaevent",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
