# Generated by Django 4.2.6 on 2023-12-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0035_alter_changelog_options_triviaevent_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="triviaevent",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_host",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
