# Generated by Django 4.2.9 on 2024-01-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_triviaevent_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiebreakerresponse',
            name='recorded_answer',
            field=models.CharField(blank=True, default='0', max_length=120),
            preserve_default=False,
        ),
    ]
